### PR TITLE
Add completion support to orgit: links

### PR DESCRIPTION
**Pull request by brianhlin**
With this I can find my target git repo much easier.

### CODE REVIEW

**Comment by tarsius** [comment]
That sounds like something worth adding. What Org command do I have to use to try this out myself?

I think `orgit-file-complete-link` should be renamed to `orgit-status-complete-link`.

**Comment by brianhlin** [comment]
You need to have `ido`, `ivy`, or even possibly `helm` file completion enabled.

1. `C-c C-l` to invoke `org-insert-link`
2. Type `orgit:<RET>`
3. You should see your preferred backend for file completion (it should look just as if you chose the `file:` org-link type above)

**Comment by tarsius** [comment]
It would be better to use `magit-read-repository`. Also if we add a completion function for this type, then we should also do so for the others. I have done that in [`completion-fns`](https://github.com/magit/orgit/compare/completion-fns?expand=1). I still have to test this a bit more and add documentation, and it might be a while until I get back to this.

**Comment by brianhlin** [comment]
I tested your changes and they appear to work but the `Revision:` completion for `orgit-log:` and `orgit-rev` links only offered `HEAD`.

**Comment by tarsius** [comment]
That's fixed now.

**Comment by tarsius** [comment]
And finally merged into master.

**Pull request closed without merging**
